// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig, env } from "prisma/config";

// Charger .env.local explicitement
config({ path: resolve(__dirname, ".env.local"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "dotenv -e .env.local -- tsx prisma/seed.ts",
  },
  // Migrations / db push utilisent la connexion directe (Neon recommande DIRECT_URL)
  datasource: {
    url: process.env.DIRECT_URL || process.env.DATABASE_URL || env("DIRECT_URL") || env("DATABASE_URL"),
  },
});
